#!/bin/sh

set -e

! [ -e compile ] && {
	printf '%s\n' "${0##*/}: "'Run ./configure to generate ./compile' >&2
	exit 1
}

export PATH="$PWD:$PATH"
alias redo-ifchange=:

mk() (
	s=$2
	set -- "$1" "$1" "$1"
	. ./"$s"
)

mk redo redo.do
while read l
do
	mk "$l" default.do
done < lnks
