#!/bin/sh

cc=${CC:-cc}
cflags='-std=c99 -Wpedantic -Wall -Werror'
cppflags='-D_POSIX_C_SOURCE=200809L'

dbg=${DEBUG:-n}

$cc --version | grep GCC >/dev/null &&
	cflags="$cflags -Wno-format-overflow"
$cc --version | grep clang >/dev/null &&
	cflags="$cflags -Wno-unused-command-line-argument"

if [ "$dbg" = y ]
then
	cflags="$cflags -O0 -g"
	cppflags="$cppflags -DDBG=1"
else
	cflags="$cflags -O2"
	cppflags="$cppflags -DDBG=0"
	dbg=n
fi

cat << EOF >&2
	configuration options:
	CC = $cc
	DEBUG = $dbg
EOF

cat <<- EOF > cc
	#!/bin/sh
	$cc $cflags $cppflags "\$@"
EOF

chmod +x cc
