#!/bin/sh

cc=${CC:-cc}
cflags='-std=c99'
cppflags='-D_POSIX_C_SOURCE=200809L'

dbg=${DEBUG:-n}

if [ "$dbg" = y ]
then
	cflags="$cflags -O0 -g -Wpedantic -Wall"
	cppflags="$cppflags -DDBG=1"
else
	cflags="$cflags -O2"
	cppflags="$cppflags -DDBG=0"
	dbg=n
fi

cat << EOF >&2
	configuration options (as read from the environment):
	CC    = $cc
	DEBUG = $dbg
	(you may also edit the generated ./cc script)
EOF

cat <<-EOF > cc
	#!/bin/sh
	$cc $cflags $cppflags "\$@"
EOF
chmod +x cc
