#!/bin/sh

set -e

icmds() {
	bindir=$1

	mkdir -p "$bindir"
	cp -f redo "$bindir"
	for lnk in ifchange ifcreate infofor
	do
		ln -sf redo "$bindir/redo-$lnk"
	done
}

ucmds() (
	bindir=$1

	cd "$bindir"
	rm -f redo redo-ifchange redo-ifcreate redo-infofor
)

iman() {
	mandir=$1

	mkdir -p "$mandir"
	cp redo.1 "$mandir"
}

uman() {
	mandir=$1

	rm -f "$mandir"/redo.1
}

usage() {
	cat <<-EOF >&2
		usage: ${0##*/} [-i|-u] [-c cmddir |-m mandir]
		-i|-u: install|uninstall (default: install)
		-c|-m dir: cmds|manual to/from dir
	EOF
	exit 1
}

op=i
c=
m=
OPTIND=1
while getopts iuc:m: fl
do
	case $fl in
	(i|u)
		op=$fl
	;;
	(c|m)
		eval "$fl=$OPTARG"
	;;
	(*)
		usage
	esac
done

[ $# -ge $OPTIND ] || [ -z "$c" ] && [ -z "$m" ] &&
	usage

[ -n "$c" ] &&
	${op}cmds "$c"

[ -n "$m" ] &&
	${op}man "$m"
true
